version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  web:
    image: oolo/wildcards-api:latest
    build:
      context: .
    environment:
      - NODE_ENV=docker
    links:
      - mongo
    ports:
      - "80:3000"
    command: npm start