version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  web:
    image: oolo/wildcards-api:latest
    build:
      context: .
    links:
      - mongo
    ports:
      - "8080:8080"
    command: npm run start